### ISSUE TITLE
non-txt files in pages should be ignored

### ISSUE THREAD

**Issue by splitbrain** [i-net-software/dokuwiki-plugin-multiorphan#1]
The plugin lists all non-txt files that are located in the pages directory as orphaned. These files should simply be ignored.

**Comment by gamma** [comment]
Ok, agreed. Out of curiosity: what kind of files could be in pages that are no DW page files?

**Comment by splitbrain** [comment]
A customer had a bunch of *.bak files in there. No idea where they came from.

**Comment by gamma** [comment]
See linked changes.
