### ISSUE TITLE
Doesn't see media inside mp3play tag

### ISSUE THREAD

**Issue by ditdotdat** [i-net-software/dokuwiki-plugin-multiorphan#11]
All the audio in our Wiki is played with the mp3play plugin. So all the links to audio media look like this:
{{mp3play>:fighting_talk_midway.mp3|}}

But Multiorphan sees those media files as orphans.

**Comment by gamma** [comment]
The plugin only supports standard links. It would be possible for plugin developers to plug into multi orphan and add more link types ...
