### ISSUE TITLE
Media files listet as orphan which are NOT orphan (used in pages)

### ISSUE THREAD

**Issue by stracfor** [i-net-software/dokuwiki-plugin-multiorphan#18]
**Version dokuwiki:** 2016-06-26 "Elenor Of Tsort"
**Version: multiorphan plugin:** 2016-08-30

**Issue description:** The following media files are listed as orphan even though they are used in pages:
**CASE A:** media file (image) in link
  `[[http://php.net|{{wiki:dokuwiki-128.png}}]]`

**CASE B:** media file in link
  `(( This is a footnote including a media file - {{video.mp4|A funny video}} ))`

**CASE C:** template default file , e. g. for the [dokuwiki template](https://www.dokuwiki.org/template:dokuwiki)
- logo.png
- favicon.ico

**Further Information:**
a) The media manager will refuse to delete the media files in case of A & B.
b) In case of pages linked in footnotes (CASE B) the pages are listed as orphan as well.

**Comment by gamma** [comment]
I tried your scenario but was unable to reproduce it. Can you please check again?
