### ISSUE TITLE
Some false positives on missing media

### ISSUE THREAD

**Issue by aubreyz** [i-net-software/dokuwiki-plugin-multiorphan#25]
Great plugin - extremely useful and thanks for writing. 

Missing media mis-identifies a small number - a few false positives. 

a) In terms of standard syntax -- media referred to within footnotes (( )) are not detected

b) I can understand that some plugins might allow media to be used in strange ways and not identified as such. However at the very least media referred to in a completely standard form but within some other syntax wrapper should be picked up:

This is not picked up:

[{{ :case:case:20060519_student_press.jpg?direct&350 |20060519 Boucher in student press}}]

I see a previous report along these lines was closed -- but it should not have been. Footnoted media is never detected.

**Comment by gamma** [comment]
a) is fixed in b862bad

I'm, not sure what you want to accomplish in b) - is this part of a plugin? Which one?

**Comment by aubreyz** [comment]
Many thanks for fixing (a), gamma. 

On (b), it happens to be from the imagebox plugin (but there will be many plugins that take completely standard syntax and wrap them in something. Whatever the case imagebox does not work (or at least did not prior to your latest commit). 

Thanks again for all your work.

**Comment by gamma** [comment]
Note: for the checks of extra plugins there are two ways to have them included during the multi orphan check:

  1) I need to update the checker which allows simple plugins to be included. 
  2) Plugin Authors can implement an event and check their syntax there.
