### ISSUE TITLE
Ignore GET variables in links

### ISSUE THREAD

**Issue by hrvojesolc** [i-net-software/dokuwiki-plugin-multiorphan#8]
Hello,

Firstly, thank you for this plugin. This is a great and handy plugin for DokuWiki.

I'm submitting this as a bug as this plugin is incorrectly triggering wanted pages if links exists to valid pages but a GET parameter is also passed.

For example, there is a valid page that exists called "navbar". It can be linked by using [[:navbar]]. However, it can also be linked via [[:navbar?do=edit]] which will automatically try to open edit window for this page or display an error to users without permissions. This plugin converts '?' and '=' to underscore and reports 'navbar_do_edit' as a wanted page. However, this is wrong as the link works and this page should show up as 'linked page' and not 'wanted page'.

Not sure about character parsing, but suggestion would be to ignore '?' character or anything past it in links, it that is permitted by DokuWiki syntax.

Thank you in advance,

Hrvoje

**Comment by gamma** [comment]
Hey,

did you uncheck the `Export all parameters (e.g. "do")` option?

**Comment by hrvojesolc** [comment]
Hello,

I can't find `Export all parameters` anywhere. I'm using `2015-08-10a "Detritus"`. I have the following options disabled:
- register
- update profile
- subscribe/unsubscribe
- set new password
- delete own account
- xml syndication

`View source/export raw` option was enabled. I tried with it disabled but same result. I have no other actions listed in other commands.

I use `.htaccess` rewrite rule (`userewrite`) with default `.htaccess` file shipped. `useslash` is checked. `sepchar` is `_`. `canonical` is unchecked and `fnencode` is `utf-8`.

Thanks again,

Hrvoje
